"""
BubbleTea Integration - Connecting to External Chat Tools

This module provides integration with BubbleTea, an external chat interface tool.
Think of it as the "bridge" that allows your ToDo Agent to work with BubbleTea's
chat interface, making your AI assistant accessible through their platform.

The integration includes:
- Configuration for how your bot appears in BubbleTea
- Request/response handling for BubbleTea's chat format
- Compatibility with BubbleTea's component system

This allows users to interact with your ToDo Agent through BubbleTea's
chat interface, providing an alternative way to access your task management system.
"""

from typing import Optional, List
from pydantic import BaseModel, Field
import bubbletea_chat as bt

# Import our ToDo Agent components
from to_do_agent.domain.agent import ToDoAgent

# ----  BubbleTea Configuration - How Your Bot Appears  ----
@bt.config()
def bubbletea_config():
    """
    Configure how your ToDo Agent appears in BubbleTea.
    
    This function tells BubbleTea about your bot - its name, appearance,
    and basic behavior. It's like setting up your bot's profile in their system.
    
    IMPORTANT: If you deploy behind API Gateway with root_path="/prod/",
    set url to your public base, e.g., "https://api.example.com/prod"
    """
    return bt.BotConfig(
        name="todo-assistant",                    # Internal name for the bot
        url="",                                   # Your public base URL (no trailing slash)
        is_streaming=False,                        # Enable real-time streaming responses
        display_name="To-Do Assistant",           # Name users see in the interface
        subtitle="Task management via chat",      # Brief description of what the bot does
        initial_text="Hi! I'm your AI task assistant. Tell me what you need to do, like 'buy milk' or 'call mom'."  # Welcome message
    )

# ----  Request Model - What BubbleTea Sends to Your Bot  ----
class ChatRequest(BaseModel):
    """
    The structure of requests that BubbleTea sends to your bot.
    
    This defines what information BubbleTea provides when a user
    sends a message to your ToDo Agent through their interface.
    """
    message: str = Field(description="The user's message to your bot")
    user_uuid: Optional[str] = Field(None, description="Unique identifier for the user")
    conversation_uuid: Optional[str] = Field(None, description="Unique identifier for the conversation")
    user_email: Optional[str] = Field(None, description="User's email address if available")
    images: Optional[List[str]] = Field(None, description="Image URLs/base64 data for vision-enabled bots")


def fastapi_config_handler():
    """
    Provide configuration information to BubbleTea.
    
    This function returns the bot configuration in the format that
    BubbleTea expects when it queries your /config endpoint.
    
    Returns:
        Bot configuration as a dictionary
    """
    # BubbleTea expects JSON of BotConfig at /config
    return bubbletea_config().__dict__

async def fastapi_chat_handler(req: ChatRequest, agent: ToDoAgent):
    """
    Handle chat requests from BubbleTea.
    
    This function processes incoming chat requests from BubbleTea
    and returns responses in the format they expect. It collects
    all the components generated by your bot and formats them properly.
    
    Args:
        req: The chat request from BubbleTea
        agent: The ToDo Agent instance (injected via dependency injection)
        
    Returns:
        BubbleTea-compatible response format with responses array
    """
    # Use conversation_uuid as conversation_id, or generate one if not provided
    conversation_id = req.conversation_uuid or f"bubbletea_{req.user_uuid or 'default'}"
    
    try:
        # Process the message through your actual ToDo Agent
        response_text = await agent.process_message(req.message, conversation_id)
        
        # Return BubbleTea-compatible response format
        return {
            "responses": [{
                "payload": [{
                    "type": "text",
                    "content": response_text
                }]
            }]
        }
        
    except Exception as e:
        # Handle any errors gracefully
        error_message = f"I'm sorry, I encountered an error: {str(e)}"
        return {
            "responses": [{
                "payload": [{
                    "type": "text",
                    "content": error_message
                }]
            }]
        }
